[package]
name = "http2shell"
version = "0.1.0"
authors = ["Francisco Miamoto <francisco@dorayaki.co>"]
edition = "2018"

[[bin]]
name = "h2s"
path = "src/main.rs"

[dependencies]
skim = "0.9.4"
structopt = "0.3.23"
reqwest = { version = "0.11", features = ["blocking", "json"] }
regex = "1"
